---
name: Test
on: [push]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: npm i
      - uses: ./
        with:
          repository: pozetroninc/github-action-get-latest-release
      - uses: ./
        with:
          owner: pozetroninc
          repo: github-action-get-latest-release
      - uses: ./
        with:
          owner: pozetroninc
          repo: github-action-get-latest-release
          excludes: prerelease, draft
      - uses: ./
        with:
          repository: pozetroninc/github-action-get-latest-release
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ./
        with:
          owner: pozetroninc
          repo: github-action-get-latest-release
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ./
        with:
          owner: pozetroninc
          repo: github-action-get-latest-release
          excludes: prerelease, draft
          token: ${{ secrets.GITHUB_TOKEN }}
